---
parser: babel-eslint

extends: eslint-config-shakacode

plugins:
  - react

env:
  browser: true
  node: true
  mocha: true

settings:
  import/resolver:
    webpack:
      config: 'webpack.config.js'